version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies needed"

  build:
    commands:
      - echo "Building static website"

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
